// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build_report.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildResult_BuildResultStatus int32

const (
	BuildResult_BUILD_RESULT_STATUS_UNSPECIFIED BuildResult_BuildResultStatus = 0
	BuildResult_SUCCESS                         BuildResult_BuildResultStatus = 1
	BuildResult_FAILURE                         BuildResult_BuildResultStatus = 2
)

var BuildResult_BuildResultStatus_name = map[int32]string{
	0: "BUILD_RESULT_STATUS_UNSPECIFIED",
	1: "SUCCESS",
	2: "FAILURE",
}

var BuildResult_BuildResultStatus_value = map[string]int32{
	"BUILD_RESULT_STATUS_UNSPECIFIED": 0,
	"SUCCESS":                         1,
	"FAILURE":                         2,
}

func (x BuildResult_BuildResultStatus) String() string {
	return proto.EnumName(BuildResult_BuildResultStatus_name, int32(x))
}

func (BuildResult_BuildResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac60b983b37b9bef, []int{1, 0}
}

type BuildResult_EarlyTerminationStatus int32

const (
	BuildResult_EARLY_TERMINATION_STATUS_UNSPECIFIED BuildResult_EarlyTerminationStatus = 0
	BuildResult_NOT_TERMINATED_EARLY                 BuildResult_EarlyTerminationStatus = 1
	BuildResult_NO_RELEVANT_CHANGES                  BuildResult_EarlyTerminationStatus = 2
)

var BuildResult_EarlyTerminationStatus_name = map[int32]string{
	0: "EARLY_TERMINATION_STATUS_UNSPECIFIED",
	1: "NOT_TERMINATED_EARLY",
	2: "NO_RELEVANT_CHANGES",
}

var BuildResult_EarlyTerminationStatus_value = map[string]int32{
	"EARLY_TERMINATION_STATUS_UNSPECIFIED": 0,
	"NOT_TERMINATED_EARLY":                 1,
	"NO_RELEVANT_CHANGES":                  2,
}

func (x BuildResult_EarlyTerminationStatus) String() string {
	return proto.EnumName(BuildResult_EarlyTerminationStatus_name, int32(x))
}

func (BuildResult_EarlyTerminationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac60b983b37b9bef, []int{1, 1}
}

// The results from one or more completed builds of Chrome OS.
type BuildReport struct {
	BuildResult          []*BuildResult `protobuf:"bytes,1,rep,name=build_result,json=buildResult,proto3" json:"build_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BuildReport) Reset()         { *m = BuildReport{} }
func (m *BuildReport) String() string { return proto.CompactTextString(m) }
func (*BuildReport) ProtoMessage()    {}
func (*BuildReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac60b983b37b9bef, []int{0}
}

func (m *BuildReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildReport.Unmarshal(m, b)
}
func (m *BuildReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildReport.Marshal(b, m, deterministic)
}
func (m *BuildReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildReport.Merge(m, src)
}
func (m *BuildReport) XXX_Size() int {
	return xxx_messageInfo_BuildReport.Size(m)
}
func (m *BuildReport) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildReport.DiscardUnknown(m)
}

var xxx_messageInfo_BuildReport proto.InternalMessageInfo

func (m *BuildReport) GetBuildResult() []*BuildResult {
	if m != nil {
		return m.BuildResult
	}
	return nil
}

// The result of a CrOS build for a single build target
type BuildResult struct {
	// A Chrome OS build target, such as "eve".
	// TODO(seanabraham): Import the common BuildTarget message once it has been
	// moved out of chromite.
	BuildTarget string `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// A Chrome OS reference design, such as "Google_Reef", or none, if there's no
	// MAINBOARD_FAMILY for this build target. Values come from
	// `mosys platform family`.
	ReferenceDesign        string                             `protobuf:"bytes,2,opt,name=reference_design,json=referenceDesign,proto3" json:"reference_design,omitempty"`
	BuildResultStatus      BuildResult_BuildResultStatus      `protobuf:"varint,3,opt,name=build_result_status,json=buildResultStatus,proto3,enum=testplans.BuildResult_BuildResultStatus" json:"build_result_status,omitempty"`
	EarlyTerminationStatus BuildResult_EarlyTerminationStatus `protobuf:"varint,4,opt,name=early_termination_status,json=earlyTerminationStatus,proto3,enum=testplans.BuildResult_EarlyTerminationStatus" json:"early_termination_status,omitempty"`
	// Google Storage path to the folder containing artifacts for the build.
	// e.g. gs://chromeos-image-archive/eve-paladin/version
	TestArtifactsPath string `protobuf:"bytes,5,opt,name=test_artifacts_path,json=testArtifactsPath,proto3" json:"test_artifacts_path,omitempty"`
	// Path to a file containing the DepGraph for the build.
	// See http://cs/chromeos_public/chromite/api/proto/depgraph.proto
	// TODO(seanabraham): Import the DepGraph message directly once it has been
	// moved out of chromite.
	DepGraphFilePath string `protobuf:"bytes,6,opt,name=dep_graph_file_path,json=depGraphFilePath,proto3" json:"dep_graph_file_path,omitempty"`
	// Details about commits that should be considered relevant for the build.
	Commit               []*Commit `protobuf:"bytes,7,rep,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BuildResult) Reset()         { *m = BuildResult{} }
func (m *BuildResult) String() string { return proto.CompactTextString(m) }
func (*BuildResult) ProtoMessage()    {}
func (*BuildResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac60b983b37b9bef, []int{1}
}

func (m *BuildResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResult.Unmarshal(m, b)
}
func (m *BuildResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResult.Marshal(b, m, deterministic)
}
func (m *BuildResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResult.Merge(m, src)
}
func (m *BuildResult) XXX_Size() int {
	return xxx_messageInfo_BuildResult.Size(m)
}
func (m *BuildResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResult.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResult proto.InternalMessageInfo

func (m *BuildResult) GetBuildTarget() string {
	if m != nil {
		return m.BuildTarget
	}
	return ""
}

func (m *BuildResult) GetReferenceDesign() string {
	if m != nil {
		return m.ReferenceDesign
	}
	return ""
}

func (m *BuildResult) GetBuildResultStatus() BuildResult_BuildResultStatus {
	if m != nil {
		return m.BuildResultStatus
	}
	return BuildResult_BUILD_RESULT_STATUS_UNSPECIFIED
}

func (m *BuildResult) GetEarlyTerminationStatus() BuildResult_EarlyTerminationStatus {
	if m != nil {
		return m.EarlyTerminationStatus
	}
	return BuildResult_EARLY_TERMINATION_STATUS_UNSPECIFIED
}

func (m *BuildResult) GetTestArtifactsPath() string {
	if m != nil {
		return m.TestArtifactsPath
	}
	return ""
}

func (m *BuildResult) GetDepGraphFilePath() string {
	if m != nil {
		return m.DepGraphFilePath
	}
	return ""
}

func (m *BuildResult) GetCommit() []*Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

type Commit struct {
	// All of the files that were affected (e.g. added, modified, deleted)
	// by this commit.
	File                 []*File  `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac60b983b37b9bef, []int{2}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

type File struct {
	// The path to a file in the Chromium/Chrome OS repos, relative to the repo
	// checkout root.
	// e.g. src/third_party/kernel/v3.8/dummyfile.dat
	SourceTreePath       string   `protobuf:"bytes,1,opt,name=source_tree_path,json=sourceTreePath,proto3" json:"source_tree_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac60b983b37b9bef, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetSourceTreePath() string {
	if m != nil {
		return m.SourceTreePath
	}
	return ""
}

func init() {
	proto.RegisterEnum("testplans.BuildResult_BuildResultStatus", BuildResult_BuildResultStatus_name, BuildResult_BuildResultStatus_value)
	proto.RegisterEnum("testplans.BuildResult_EarlyTerminationStatus", BuildResult_EarlyTerminationStatus_name, BuildResult_EarlyTerminationStatus_value)
	proto.RegisterType((*BuildReport)(nil), "testplans.BuildReport")
	proto.RegisterType((*BuildResult)(nil), "testplans.BuildResult")
	proto.RegisterType((*Commit)(nil), "testplans.Commit")
	proto.RegisterType((*File)(nil), "testplans.File")
}

func init() { proto.RegisterFile("build_report.proto", fileDescriptor_ac60b983b37b9bef) }

var fileDescriptor_ac60b983b37b9bef = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0xfd, 0xa0, 0x7c, 0x74, 0xbd, 0x4c, 0x6d, 0x30, 0x13, 0xcb, 0xdb, 0xba, 0x74, 0x0f, 0xe9,
	0x03, 0x68, 0xea, 0x9e, 0xf6, 0x18, 0xc0, 0xb4, 0x91, 0xb2, 0x50, 0x39, 0xce, 0xb4, 0xed, 0xc5,
	0x32, 0x60, 0x20, 0x52, 0x48, 0x22, 0xc7, 0x79, 0xd8, 0xef, 0xde, 0x1f, 0x98, 0xec, 0x04, 0x8a,
	0x36, 0xf6, 0x94, 0xdc, 0x73, 0xce, 0x3d, 0xb9, 0xf7, 0xc4, 0x06, 0xb4, 0xac, 0x92, 0x74, 0xcd,
	0xa4, 0x28, 0x72, 0xa9, 0xc6, 0x85, 0xcc, 0x55, 0x8e, 0xae, 0x94, 0x28, 0x55, 0x91, 0xf2, 0xac,
	0x74, 0x9e, 0xa0, 0x37, 0xd1, 0x02, 0x62, 0x78, 0xf4, 0x19, 0x5e, 0x1f, 0xf4, 0x65, 0x95, 0x2a,
	0xbb, 0x75, 0x7b, 0xe1, 0xf6, 0x1e, 0x86, 0xe3, 0x63, 0xc3, 0xb8, 0x51, 0x6b, 0x96, 0xf4, 0x96,
	0x2f, 0x85, 0xf3, 0xab, 0x73, 0xb4, 0xd2, 0x35, 0x7a, 0x7f, 0xb0, 0x52, 0x5c, 0x6e, 0x85, 0xb6,
	0x6a, 0xb9, 0x57, 0x4d, 0x0b, 0x35, 0x10, 0xba, 0x07, 0x4b, 0x8a, 0x8d, 0x90, 0x22, 0x5b, 0x09,
	0xb6, 0x16, 0x65, 0xb2, 0xcd, 0xec, 0xb6, 0x91, 0xdd, 0x1c, 0xf1, 0x99, 0x81, 0xd1, 0x37, 0x18,
	0x9c, 0x0e, 0xc6, 0x4a, 0xc5, 0x55, 0x55, 0xda, 0x17, 0xb7, 0x2d, 0xf7, 0xfa, 0xc1, 0x3d, 0x3f,
	0xdf, 0xe9, 0x7b, 0x64, 0xf4, 0xa4, 0xbf, 0xfc, 0x13, 0x42, 0x5b, 0xb0, 0x05, 0x97, 0xe9, 0x4f,
	0xa6, 0x84, 0xdc, 0x27, 0x19, 0x57, 0x49, 0x9e, 0x1d, 0xec, 0x3b, 0xc6, 0x7e, 0xf4, 0x0f, 0x7b,
	0xac, 0xdb, 0xe8, 0x4b, 0x57, 0xf3, 0x8d, 0xa1, 0x38, 0x8b, 0xa3, 0x31, 0x0c, 0xb4, 0x0f, 0xe3,
	0x52, 0x25, 0x1b, 0xbe, 0x52, 0x25, 0x2b, 0xb8, 0xda, 0xd9, 0xff, 0x9b, 0x85, 0xfb, 0x9a, 0xf2,
	0x0e, 0xcc, 0x33, 0x57, 0x3b, 0x34, 0x82, 0xc1, 0x5a, 0x14, 0x6c, 0x2b, 0x79, 0xb1, 0x63, 0x9b,
	0x24, 0x15, 0xb5, 0xbe, 0x6b, 0xf4, 0xd6, 0x5a, 0x14, 0x8f, 0x9a, 0x99, 0x27, 0xa9, 0x30, 0xf2,
	0x7b, 0xe8, 0xae, 0xf2, 0xfd, 0x3e, 0x51, 0xf6, 0xa5, 0xf9, 0x69, 0xfd, 0x93, 0xa9, 0xa7, 0x86,
	0x20, 0x8d, 0xc0, 0x21, 0xd0, 0xff, 0x2b, 0x1a, 0x74, 0x07, 0xef, 0x26, 0xb1, 0x1f, 0xcc, 0x18,
	0xc1, 0x51, 0x1c, 0x50, 0x16, 0x51, 0x8f, 0xc6, 0x11, 0x8b, 0xc3, 0xe8, 0x19, 0x4f, 0xfd, 0xb9,
	0x8f, 0x67, 0xd6, 0x7f, 0xa8, 0x07, 0x97, 0x51, 0x3c, 0x9d, 0xe2, 0x28, 0xb2, 0x5a, 0xba, 0x98,
	0x7b, 0x7e, 0x10, 0x13, 0x6c, 0xb5, 0x9d, 0x0a, 0x86, 0xe7, 0xf3, 0x40, 0x2e, 0x7c, 0xc0, 0x1e,
	0x09, 0xbe, 0x33, 0x8a, 0xc9, 0x17, 0x3f, 0xf4, 0xa8, 0xbf, 0x08, 0xcf, 0xbb, 0xdb, 0xf0, 0x26,
	0x5c, 0xd0, 0xa3, 0x0e, 0xcf, 0x98, 0x69, 0xb4, 0x5a, 0xe8, 0x2d, 0x0c, 0xc2, 0x05, 0x23, 0x38,
	0xc0, 0x5f, 0xbd, 0x90, 0xb2, 0xe9, 0x93, 0x17, 0x3e, 0xe2, 0xc8, 0x6a, 0x3b, 0x23, 0xe8, 0xd6,
	0xcb, 0xa1, 0x3b, 0xe8, 0xe8, 0x90, 0x9a, 0x23, 0x7b, 0x73, 0xb2, 0xbd, 0x8e, 0x88, 0x18, 0xd2,
	0xf9, 0x08, 0x1d, 0x5d, 0x21, 0x17, 0xac, 0x32, 0xaf, 0xe4, 0x4a, 0x30, 0x25, 0x45, 0x13, 0x6c,
	0x7d, 0x40, 0xaf, 0x6b, 0x9c, 0x4a, 0x61, 0x62, 0x9d, 0xbc, 0xfa, 0xd1, 0x35, 0x97, 0xa6, 0x5c,
	0xd6, 0xcf, 0x4f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x5d, 0x46, 0xeb, 0x52, 0x03, 0x00,
	0x00,
}
