// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generate_test_plan.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	config "go.chromium.org/luci/lucicfg/external/crostesting/proto/config"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilePath struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilePath) Reset()         { *m = FilePath{} }
func (m *FilePath) String() string { return proto.CompactTextString(m) }
func (*FilePath) ProtoMessage()    {}
func (*FilePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{0}
}

func (m *FilePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePath.Unmarshal(m, b)
}
func (m *FilePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePath.Marshal(b, m, deterministic)
}
func (m *FilePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePath.Merge(m, src)
}
func (m *FilePath) XXX_Size() int {
	return xxx_messageInfo_FilePath.Size(m)
}
func (m *FilePath) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePath.DiscardUnknown(m)
}

var xxx_messageInfo_FilePath proto.InternalMessageInfo

func (m *FilePath) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type GenerateTestPlanRequest struct {
	// Path on disk to source_tree_test_config.cfg, which lives in chromite.
	SourceTreeConfigPath string `protobuf:"bytes,1,opt,name=source_tree_config_path,json=sourceTreeConfigPath,proto3" json:"source_tree_config_path,omitempty"`
	// Path on disk to target_test_requirements.cfg, which lives in chromite.
	TargetTestRequirementsPath string `protobuf:"bytes,2,opt,name=target_test_requirements_path,json=targetTestRequirementsPath,proto3" json:"target_test_requirements_path,omitempty"`
	// Path on disk to a BuildReport in protobuf JSON format.
	BuildReportPath      []*FilePath `protobuf:"bytes,3,rep,name=build_report_path,json=buildReportPath,proto3" json:"build_report_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenerateTestPlanRequest) Reset()         { *m = GenerateTestPlanRequest{} }
func (m *GenerateTestPlanRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateTestPlanRequest) ProtoMessage()    {}
func (*GenerateTestPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{1}
}

func (m *GenerateTestPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTestPlanRequest.Unmarshal(m, b)
}
func (m *GenerateTestPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTestPlanRequest.Marshal(b, m, deterministic)
}
func (m *GenerateTestPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTestPlanRequest.Merge(m, src)
}
func (m *GenerateTestPlanRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateTestPlanRequest.Size(m)
}
func (m *GenerateTestPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTestPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTestPlanRequest proto.InternalMessageInfo

func (m *GenerateTestPlanRequest) GetSourceTreeConfigPath() string {
	if m != nil {
		return m.SourceTreeConfigPath
	}
	return ""
}

func (m *GenerateTestPlanRequest) GetTargetTestRequirementsPath() string {
	if m != nil {
		return m.TargetTestRequirementsPath
	}
	return ""
}

func (m *GenerateTestPlanRequest) GetBuildReportPath() []*FilePath {
	if m != nil {
		return m.BuildReportPath
	}
	return nil
}

// The final test plan.
type GenerateTestPlanResponse struct {
	TestUnit             []*TestUnit `protobuf:"bytes,1,rep,name=test_unit,json=testUnit,proto3" json:"test_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenerateTestPlanResponse) Reset()         { *m = GenerateTestPlanResponse{} }
func (m *GenerateTestPlanResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateTestPlanResponse) ProtoMessage()    {}
func (*GenerateTestPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{2}
}

func (m *GenerateTestPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTestPlanResponse.Unmarshal(m, b)
}
func (m *GenerateTestPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTestPlanResponse.Marshal(b, m, deterministic)
}
func (m *GenerateTestPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTestPlanResponse.Merge(m, src)
}
func (m *GenerateTestPlanResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateTestPlanResponse.Size(m)
}
func (m *GenerateTestPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTestPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTestPlanResponse proto.InternalMessageInfo

func (m *GenerateTestPlanResponse) GetTestUnit() []*TestUnit {
	if m != nil {
		return m.TestUnit
	}
	return nil
}

// A Chromium build image, such as "kevin".
type Image struct {
	// The build image's name.
	ImageName            string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{3}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

// The files that should be tested in a test plan.
type BuildPayload struct {
	// We expect to use either version or images, but not both.
	// We'll drop the unnecessary one once we've sorted out details
	// with the Skylab team.
	Version string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Image   []*Image `protobuf:"bytes,2,rep,name=image,proto3" json:"image,omitempty"`
	// The location in Google Storage of the artifacts for this build.
	// e.g. gs://chromeos-image-archive/eve-paladin/R73-11588.0.0-rc4
	ArtifactPath         string   `protobuf:"bytes,3,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildPayload) Reset()         { *m = BuildPayload{} }
func (m *BuildPayload) String() string { return proto.CompactTextString(m) }
func (*BuildPayload) ProtoMessage()    {}
func (*BuildPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{4}
}

func (m *BuildPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildPayload.Unmarshal(m, b)
}
func (m *BuildPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildPayload.Marshal(b, m, deterministic)
}
func (m *BuildPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildPayload.Merge(m, src)
}
func (m *BuildPayload) XXX_Size() int {
	return xxx_messageInfo_BuildPayload.Size(m)
}
func (m *BuildPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BuildPayload proto.InternalMessageInfo

func (m *BuildPayload) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BuildPayload) GetImage() []*Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *BuildPayload) GetArtifactPath() string {
	if m != nil {
		return m.ArtifactPath
	}
	return ""
}

// Hardware or VM requirements for running a test plan.
type SchedulingRequirements struct {
	// Types that are valid to be assigned to TargetType:
	//	*SchedulingRequirements_ReferenceDesign
	//	*SchedulingRequirements_BuildTarget
	TargetType           isSchedulingRequirements_TargetType `protobuf_oneof:"target_type"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *SchedulingRequirements) Reset()         { *m = SchedulingRequirements{} }
func (m *SchedulingRequirements) String() string { return proto.CompactTextString(m) }
func (*SchedulingRequirements) ProtoMessage()    {}
func (*SchedulingRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{5}
}

func (m *SchedulingRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingRequirements.Unmarshal(m, b)
}
func (m *SchedulingRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingRequirements.Marshal(b, m, deterministic)
}
func (m *SchedulingRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingRequirements.Merge(m, src)
}
func (m *SchedulingRequirements) XXX_Size() int {
	return xxx_messageInfo_SchedulingRequirements.Size(m)
}
func (m *SchedulingRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingRequirements proto.InternalMessageInfo

type isSchedulingRequirements_TargetType interface {
	isSchedulingRequirements_TargetType()
}

type SchedulingRequirements_ReferenceDesign struct {
	ReferenceDesign string `protobuf:"bytes,1,opt,name=reference_design,json=referenceDesign,proto3,oneof"`
}

type SchedulingRequirements_BuildTarget struct {
	BuildTarget string `protobuf:"bytes,2,opt,name=build_target,json=buildTarget,proto3,oneof"`
}

func (*SchedulingRequirements_ReferenceDesign) isSchedulingRequirements_TargetType() {}

func (*SchedulingRequirements_BuildTarget) isSchedulingRequirements_TargetType() {}

func (m *SchedulingRequirements) GetTargetType() isSchedulingRequirements_TargetType {
	if m != nil {
		return m.TargetType
	}
	return nil
}

func (m *SchedulingRequirements) GetReferenceDesign() string {
	if x, ok := m.GetTargetType().(*SchedulingRequirements_ReferenceDesign); ok {
		return x.ReferenceDesign
	}
	return ""
}

func (m *SchedulingRequirements) GetBuildTarget() string {
	if x, ok := m.GetTargetType().(*SchedulingRequirements_BuildTarget); ok {
		return x.BuildTarget
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchedulingRequirements) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchedulingRequirements_ReferenceDesign)(nil),
		(*SchedulingRequirements_BuildTarget)(nil),
	}
}

// Metadata for executing one test configuration for one reference design or
// build target.
type TestUnit struct {
	// Types that are valid to be assigned to TestCfg:
	//	*TestUnit_GceTestCfg
	//	*TestUnit_HwTestCfg
	//	*TestUnit_MoblabVmTestCfg
	//	*TestUnit_TastVmTestCfg
	//	*TestUnit_VmTestCfg
	TestCfg isTestUnit_TestCfg `protobuf_oneof:"TestCfg"`
	// The scheduling requirements for this test plan.
	SchedulingRequirements *SchedulingRequirements `protobuf:"bytes,6,opt,name=scheduling_requirements,json=schedulingRequirements,proto3" json:"scheduling_requirements,omitempty"`
	// The build files provided to run this test plan.
	BuildPayload         *BuildPayload `protobuf:"bytes,7,opt,name=build_payload,json=buildPayload,proto3" json:"build_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TestUnit) Reset()         { *m = TestUnit{} }
func (m *TestUnit) String() string { return proto.CompactTextString(m) }
func (*TestUnit) ProtoMessage()    {}
func (*TestUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_399f7dfd41039e0b, []int{6}
}

func (m *TestUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestUnit.Unmarshal(m, b)
}
func (m *TestUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestUnit.Marshal(b, m, deterministic)
}
func (m *TestUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestUnit.Merge(m, src)
}
func (m *TestUnit) XXX_Size() int {
	return xxx_messageInfo_TestUnit.Size(m)
}
func (m *TestUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_TestUnit.DiscardUnknown(m)
}

var xxx_messageInfo_TestUnit proto.InternalMessageInfo

type isTestUnit_TestCfg interface {
	isTestUnit_TestCfg()
}

type TestUnit_GceTestCfg struct {
	GceTestCfg *config.GceTestCfg `protobuf:"bytes,1,opt,name=gce_test_cfg,json=gceTestCfg,proto3,oneof"`
}

type TestUnit_HwTestCfg struct {
	HwTestCfg *config.HwTestCfg `protobuf:"bytes,2,opt,name=hw_test_cfg,json=hwTestCfg,proto3,oneof"`
}

type TestUnit_MoblabVmTestCfg struct {
	MoblabVmTestCfg *config.MoblabVmTestCfg `protobuf:"bytes,3,opt,name=moblab_vm_test_cfg,json=moblabVmTestCfg,proto3,oneof"`
}

type TestUnit_TastVmTestCfg struct {
	TastVmTestCfg *config.TastVmTestCfg `protobuf:"bytes,4,opt,name=tast_vm_test_cfg,json=tastVmTestCfg,proto3,oneof"`
}

type TestUnit_VmTestCfg struct {
	VmTestCfg *config.VmTestCfg `protobuf:"bytes,5,opt,name=vm_test_cfg,json=vmTestCfg,proto3,oneof"`
}

func (*TestUnit_GceTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_HwTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_MoblabVmTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_TastVmTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_VmTestCfg) isTestUnit_TestCfg() {}

func (m *TestUnit) GetTestCfg() isTestUnit_TestCfg {
	if m != nil {
		return m.TestCfg
	}
	return nil
}

func (m *TestUnit) GetGceTestCfg() *config.GceTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_GceTestCfg); ok {
		return x.GceTestCfg
	}
	return nil
}

func (m *TestUnit) GetHwTestCfg() *config.HwTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_HwTestCfg); ok {
		return x.HwTestCfg
	}
	return nil
}

func (m *TestUnit) GetMoblabVmTestCfg() *config.MoblabVmTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_MoblabVmTestCfg); ok {
		return x.MoblabVmTestCfg
	}
	return nil
}

func (m *TestUnit) GetTastVmTestCfg() *config.TastVmTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_TastVmTestCfg); ok {
		return x.TastVmTestCfg
	}
	return nil
}

func (m *TestUnit) GetVmTestCfg() *config.VmTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_VmTestCfg); ok {
		return x.VmTestCfg
	}
	return nil
}

func (m *TestUnit) GetSchedulingRequirements() *SchedulingRequirements {
	if m != nil {
		return m.SchedulingRequirements
	}
	return nil
}

func (m *TestUnit) GetBuildPayload() *BuildPayload {
	if m != nil {
		return m.BuildPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestUnit) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestUnit_GceTestCfg)(nil),
		(*TestUnit_HwTestCfg)(nil),
		(*TestUnit_MoblabVmTestCfg)(nil),
		(*TestUnit_TastVmTestCfg)(nil),
		(*TestUnit_VmTestCfg)(nil),
	}
}

func init() {
	proto.RegisterType((*FilePath)(nil), "testplans.FilePath")
	proto.RegisterType((*GenerateTestPlanRequest)(nil), "testplans.GenerateTestPlanRequest")
	proto.RegisterType((*GenerateTestPlanResponse)(nil), "testplans.GenerateTestPlanResponse")
	proto.RegisterType((*Image)(nil), "testplans.Image")
	proto.RegisterType((*BuildPayload)(nil), "testplans.BuildPayload")
	proto.RegisterType((*SchedulingRequirements)(nil), "testplans.SchedulingRequirements")
	proto.RegisterType((*TestUnit)(nil), "testplans.TestUnit")
}

func init() { proto.RegisterFile("generate_test_plan.proto", fileDescriptor_399f7dfd41039e0b) }

var fileDescriptor_399f7dfd41039e0b = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x6d, 0x6b, 0xd3, 0x50,
	0x14, 0x5e, 0x57, 0xb7, 0x35, 0xa7, 0x2d, 0x9b, 0x57, 0x59, 0xc3, 0x74, 0x30, 0x3b, 0x98, 0x03,
	0xa1, 0x95, 0x89, 0x20, 0x28, 0x88, 0x9d, 0xba, 0x8a, 0x6f, 0x23, 0x56, 0x3f, 0xec, 0x4b, 0xb8,
	0x4d, 0x4f, 0xd2, 0x0b, 0xc9, 0x4d, 0x76, 0xef, 0xcd, 0xe6, 0xfe, 0xa7, 0x3f, 0xc5, 0x1f, 0x20,
	0x39, 0x37, 0x6d, 0x13, 0x36, 0x3f, 0xf5, 0x9e, 0x97, 0xe7, 0x39, 0x2f, 0xcf, 0x69, 0xc0, 0x8d,
	0x50, 0xa2, 0xe2, 0x06, 0x7d, 0x83, 0xda, 0xf8, 0x59, 0xcc, 0xe5, 0x20, 0x53, 0xa9, 0x49, 0x99,
	0x53, 0x38, 0x0a, 0x5b, 0xef, 0x7d, 0x8f, 0xf3, 0x40, 0x04, 0x61, 0x34, 0xc4, 0xdf, 0x06, 0x95,
	0xe4, 0xf1, 0x30, 0x50, 0xa9, 0x2e, 0xe2, 0x42, 0x46, 0x43, 0x4a, 0x1f, 0x06, 0xa9, 0x0c, 0x45,
	0x34, 0x34, 0x5c, 0x45, 0x68, 0x2c, 0x99, 0xc2, 0xcb, 0x5c, 0x28, 0x4c, 0x50, 0x1a, 0xed, 0xdb,
	0xb8, 0xe5, 0xee, 0x3f, 0x85, 0xd6, 0x47, 0x11, 0xe3, 0x39, 0x37, 0x73, 0xf6, 0x08, 0x9c, 0x50,
	0xc4, 0xe8, 0x67, 0xdc, 0xcc, 0xdd, 0xc6, 0x41, 0xe3, 0xd8, 0xf1, 0x5a, 0x61, 0x19, 0xec, 0xff,
	0x69, 0x40, 0xef, 0xac, 0xec, 0x70, 0x82, 0xda, 0x9c, 0xc7, 0x5c, 0x7a, 0x78, 0x99, 0xa3, 0x36,
	0xec, 0x25, 0xf4, 0x74, 0x9a, 0xab, 0x00, 0x7d, 0xa3, 0x10, 0xcb, 0x02, 0x55, 0x9a, 0x87, 0x36,
	0x3c, 0x51, 0x88, 0xa7, 0x14, 0xa4, 0x7a, 0xef, 0x60, 0xff, 0xbf, 0x4d, 0x12, 0x78, 0x9d, 0xc0,
	0x7b, 0x36, 0xa9, 0x28, 0xea, 0x55, 0x52, 0x88, 0xe2, 0x2d, 0xdc, 0x9f, 0xe6, 0x22, 0x9e, 0xf9,
	0x0a, 0xb3, 0x54, 0x19, 0x0b, 0x6b, 0x1e, 0x34, 0x8f, 0xdb, 0x27, 0x0f, 0x06, 0xcb, 0xb5, 0x0d,
	0x16, 0x23, 0x7a, 0xdb, 0x94, 0xed, 0x51, 0x32, 0x8d, 0xf5, 0x05, 0xdc, 0xdb, 0x53, 0xe9, 0x2c,
	0x95, 0x1a, 0xd9, 0x73, 0xa0, 0xcd, 0xfb, 0xb9, 0x14, 0xc6, 0x6d, 0xdc, 0x22, 0x2d, 0xf2, 0x7f,
	0x4a, 0x61, 0xbc, 0x96, 0x29, 0x5f, 0xfd, 0x23, 0xd8, 0xf8, 0x94, 0xf0, 0x08, 0xd9, 0x3e, 0x80,
	0x28, 0x1e, 0xbe, 0xe4, 0x09, 0x96, 0x4b, 0x70, 0xc8, 0xf3, 0x8d, 0x27, 0xd8, 0xcf, 0xa1, 0x33,
	0x2a, 0x1a, 0x39, 0xe7, 0x37, 0x71, 0xca, 0x67, 0xcc, 0x85, 0xad, 0x2b, 0x54, 0x5a, 0xa4, 0xb2,
	0xcc, 0x5d, 0x98, 0xec, 0x08, 0x36, 0x08, 0xe6, 0xae, 0x53, 0xfd, 0x9d, 0x4a, 0x7d, 0xaa, 0xe4,
	0xd9, 0x30, 0x3b, 0x84, 0x2e, 0x57, 0x46, 0x84, 0x3c, 0x58, 0x2e, 0xa1, 0xe0, 0xe9, 0x2c, 0x9c,
	0x34, 0xec, 0x0d, 0xec, 0xfe, 0x08, 0xe6, 0x38, 0xcb, 0x63, 0x21, 0xa3, 0xea, 0x2e, 0xd9, 0x33,
	0xd8, 0x51, 0x18, 0xa2, 0x42, 0x19, 0xa0, 0x3f, 0x43, 0x2d, 0xa2, 0xb2, 0x93, 0xf1, 0x9a, 0xb7,
	0xbd, 0x8c, 0xbc, 0xa7, 0x00, 0x3b, 0x84, 0x8e, 0x5d, 0xba, 0x15, 0xc6, 0xca, 0x34, 0x5e, 0xf3,
	0xda, 0xe4, 0x9d, 0x90, 0x73, 0xd4, 0x85, 0xf6, 0x42, 0xdc, 0x9b, 0x0c, 0xfb, 0x7f, 0x9b, 0xd0,
	0x5a, 0x2c, 0x8c, 0xbd, 0x86, 0x4e, 0x14, 0x94, 0x77, 0x1e, 0x84, 0x11, 0x55, 0x6a, 0x9f, 0xf4,
	0x06, 0x95, 0x5b, 0x1e, 0x9c, 0x05, 0x24, 0xc8, 0x69, 0x18, 0x8d, 0xd7, 0x3c, 0x88, 0x96, 0x16,
	0x7b, 0x05, 0xed, 0xf9, 0xf5, 0x0a, 0xbb, 0x4e, 0xd8, 0xdd, 0x1a, 0x76, 0x7c, 0xbd, 0x82, 0x3a,
	0xf3, 0x85, 0xc1, 0x3e, 0x03, 0x4b, 0xd2, 0x69, 0xcc, 0xa7, 0xfe, 0x55, 0xb2, 0x22, 0x68, 0x12,
	0xc1, 0xe3, 0x1a, 0xc1, 0x57, 0x4a, 0xfb, 0x95, 0xac, 0x68, 0xb6, 0x93, 0xba, 0x8b, 0x7d, 0x80,
	0x1d, 0xc3, 0xb5, 0xa9, 0x51, 0xdd, 0x23, 0xaa, 0xbd, 0x1a, 0xd5, 0x84, 0x6b, 0x53, 0x25, 0xea,
	0x9a, 0xaa, 0xa3, 0x98, 0xa6, 0xca, 0xb0, 0x71, 0xc7, 0x34, 0x55, 0xb4, 0x73, 0xb5, 0x44, 0x5e,
	0x40, 0x4f, 0x2f, 0xc5, 0xac, 0xfd, 0x79, 0xdc, 0x4d, 0x62, 0x79, 0x52, 0xb9, 0x95, 0xbb, 0x65,
	0xf7, 0x76, 0xf5, 0xdd, 0xe7, 0xf0, 0x06, 0xba, 0x56, 0xe1, 0xcc, 0x1e, 0xa8, 0xbb, 0x55, 0x2a,
	0xb4, 0x62, 0xac, 0xde, 0xaf, 0x67, 0xef, 0xa1, 0xb4, 0x46, 0x0e, 0x6c, 0x95, 0x4d, 0x8e, 0x5a,
	0x17, 0x9b, 0xf4, 0x9d, 0xd1, 0x53, 0xfb, 0xfb, 0xe2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0x1a, 0xe0, 0xd3, 0xe7, 0x04, 0x00, 0x00,
}
