// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_plan.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	config "go.chromium.org/luci/lucicfg/external/crostesting/proto/config"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Chromium build image, such as "kevin".
type Image struct {
	// The build image's name.
	ImageName            string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfe14786b7f13cd, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

// The files that should be tested in a test plan.
type BuildPayload struct {
	// We expect to use either version or images, but not both.
	// We'll drop the unnecessary one once we've sorted out details
	// with the Skylab team.
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Image                []*Image `protobuf:"bytes,2,rep,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildPayload) Reset()         { *m = BuildPayload{} }
func (m *BuildPayload) String() string { return proto.CompactTextString(m) }
func (*BuildPayload) ProtoMessage()    {}
func (*BuildPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfe14786b7f13cd, []int{1}
}

func (m *BuildPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildPayload.Unmarshal(m, b)
}
func (m *BuildPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildPayload.Marshal(b, m, deterministic)
}
func (m *BuildPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildPayload.Merge(m, src)
}
func (m *BuildPayload) XXX_Size() int {
	return xxx_messageInfo_BuildPayload.Size(m)
}
func (m *BuildPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BuildPayload proto.InternalMessageInfo

func (m *BuildPayload) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BuildPayload) GetImage() []*Image {
	if m != nil {
		return m.Image
	}
	return nil
}

// Hardware or VM requirements for running a test plan.
type SchedulingRequirements struct {
	// Types that are valid to be assigned to TargetType:
	//	*SchedulingRequirements_ReferenceDesign
	//	*SchedulingRequirements_BuildTarget
	TargetType           isSchedulingRequirements_TargetType `protobuf_oneof:"target_type"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *SchedulingRequirements) Reset()         { *m = SchedulingRequirements{} }
func (m *SchedulingRequirements) String() string { return proto.CompactTextString(m) }
func (*SchedulingRequirements) ProtoMessage()    {}
func (*SchedulingRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfe14786b7f13cd, []int{2}
}

func (m *SchedulingRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingRequirements.Unmarshal(m, b)
}
func (m *SchedulingRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingRequirements.Marshal(b, m, deterministic)
}
func (m *SchedulingRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingRequirements.Merge(m, src)
}
func (m *SchedulingRequirements) XXX_Size() int {
	return xxx_messageInfo_SchedulingRequirements.Size(m)
}
func (m *SchedulingRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingRequirements proto.InternalMessageInfo

type isSchedulingRequirements_TargetType interface {
	isSchedulingRequirements_TargetType()
}

type SchedulingRequirements_ReferenceDesign struct {
	ReferenceDesign string `protobuf:"bytes,1,opt,name=reference_design,json=referenceDesign,proto3,oneof"`
}

type SchedulingRequirements_BuildTarget struct {
	BuildTarget string `protobuf:"bytes,2,opt,name=build_target,json=buildTarget,proto3,oneof"`
}

func (*SchedulingRequirements_ReferenceDesign) isSchedulingRequirements_TargetType() {}

func (*SchedulingRequirements_BuildTarget) isSchedulingRequirements_TargetType() {}

func (m *SchedulingRequirements) GetTargetType() isSchedulingRequirements_TargetType {
	if m != nil {
		return m.TargetType
	}
	return nil
}

func (m *SchedulingRequirements) GetReferenceDesign() string {
	if x, ok := m.GetTargetType().(*SchedulingRequirements_ReferenceDesign); ok {
		return x.ReferenceDesign
	}
	return ""
}

func (m *SchedulingRequirements) GetBuildTarget() string {
	if x, ok := m.GetTargetType().(*SchedulingRequirements_BuildTarget); ok {
		return x.BuildTarget
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchedulingRequirements) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchedulingRequirements_ReferenceDesign)(nil),
		(*SchedulingRequirements_BuildTarget)(nil),
	}
}

// Metadata for executing one test configuration for one reference design or
// build target.
type TestPlan struct {
	// Types that are valid to be assigned to TestCfg:
	//	*TestPlan_GceTestCfg
	//	*TestPlan_HwTestCfg
	//	*TestPlan_MoblabVmTestCfg
	//	*TestPlan_TastVmTestCfg
	//	*TestPlan_VmTestCfg
	TestCfg isTestPlan_TestCfg `protobuf_oneof:"TestCfg"`
	// The scheduling requirements for this test plan.
	SchedulingRequirements *SchedulingRequirements `protobuf:"bytes,6,opt,name=scheduling_requirements,json=schedulingRequirements,proto3" json:"scheduling_requirements,omitempty"`
	// The build files provided to run this test plan.
	BuildPayload         *BuildPayload `protobuf:"bytes,7,opt,name=build_payload,json=buildPayload,proto3" json:"build_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TestPlan) Reset()         { *m = TestPlan{} }
func (m *TestPlan) String() string { return proto.CompactTextString(m) }
func (*TestPlan) ProtoMessage()    {}
func (*TestPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfe14786b7f13cd, []int{3}
}

func (m *TestPlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPlan.Unmarshal(m, b)
}
func (m *TestPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPlan.Marshal(b, m, deterministic)
}
func (m *TestPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPlan.Merge(m, src)
}
func (m *TestPlan) XXX_Size() int {
	return xxx_messageInfo_TestPlan.Size(m)
}
func (m *TestPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPlan.DiscardUnknown(m)
}

var xxx_messageInfo_TestPlan proto.InternalMessageInfo

type isTestPlan_TestCfg interface {
	isTestPlan_TestCfg()
}

type TestPlan_GceTestCfg struct {
	GceTestCfg *config.GceTestCfg `protobuf:"bytes,1,opt,name=gce_test_cfg,json=gceTestCfg,proto3,oneof"`
}

type TestPlan_HwTestCfg struct {
	HwTestCfg *config.HwTestCfg `protobuf:"bytes,2,opt,name=hw_test_cfg,json=hwTestCfg,proto3,oneof"`
}

type TestPlan_MoblabVmTestCfg struct {
	MoblabVmTestCfg *config.MoblabVmTestCfg `protobuf:"bytes,3,opt,name=moblab_vm_test_cfg,json=moblabVmTestCfg,proto3,oneof"`
}

type TestPlan_TastVmTestCfg struct {
	TastVmTestCfg *config.TastVmTestCfg `protobuf:"bytes,4,opt,name=tast_vm_test_cfg,json=tastVmTestCfg,proto3,oneof"`
}

type TestPlan_VmTestCfg struct {
	VmTestCfg *config.VmTestCfg `protobuf:"bytes,5,opt,name=vm_test_cfg,json=vmTestCfg,proto3,oneof"`
}

func (*TestPlan_GceTestCfg) isTestPlan_TestCfg() {}

func (*TestPlan_HwTestCfg) isTestPlan_TestCfg() {}

func (*TestPlan_MoblabVmTestCfg) isTestPlan_TestCfg() {}

func (*TestPlan_TastVmTestCfg) isTestPlan_TestCfg() {}

func (*TestPlan_VmTestCfg) isTestPlan_TestCfg() {}

func (m *TestPlan) GetTestCfg() isTestPlan_TestCfg {
	if m != nil {
		return m.TestCfg
	}
	return nil
}

func (m *TestPlan) GetGceTestCfg() *config.GceTestCfg {
	if x, ok := m.GetTestCfg().(*TestPlan_GceTestCfg); ok {
		return x.GceTestCfg
	}
	return nil
}

func (m *TestPlan) GetHwTestCfg() *config.HwTestCfg {
	if x, ok := m.GetTestCfg().(*TestPlan_HwTestCfg); ok {
		return x.HwTestCfg
	}
	return nil
}

func (m *TestPlan) GetMoblabVmTestCfg() *config.MoblabVmTestCfg {
	if x, ok := m.GetTestCfg().(*TestPlan_MoblabVmTestCfg); ok {
		return x.MoblabVmTestCfg
	}
	return nil
}

func (m *TestPlan) GetTastVmTestCfg() *config.TastVmTestCfg {
	if x, ok := m.GetTestCfg().(*TestPlan_TastVmTestCfg); ok {
		return x.TastVmTestCfg
	}
	return nil
}

func (m *TestPlan) GetVmTestCfg() *config.VmTestCfg {
	if x, ok := m.GetTestCfg().(*TestPlan_VmTestCfg); ok {
		return x.VmTestCfg
	}
	return nil
}

func (m *TestPlan) GetSchedulingRequirements() *SchedulingRequirements {
	if m != nil {
		return m.SchedulingRequirements
	}
	return nil
}

func (m *TestPlan) GetBuildPayload() *BuildPayload {
	if m != nil {
		return m.BuildPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestPlan) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestPlan_GceTestCfg)(nil),
		(*TestPlan_HwTestCfg)(nil),
		(*TestPlan_MoblabVmTestCfg)(nil),
		(*TestPlan_TastVmTestCfg)(nil),
		(*TestPlan_VmTestCfg)(nil),
	}
}

// A full set of test plans for a given CQ run.
type CombinedTestPlan struct {
	// The test plans needed to satisfy this CQ run.
	TestPlan             []*TestPlan `protobuf:"bytes,1,rep,name=test_plan,json=testPlan,proto3" json:"test_plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CombinedTestPlan) Reset()         { *m = CombinedTestPlan{} }
func (m *CombinedTestPlan) String() string { return proto.CompactTextString(m) }
func (*CombinedTestPlan) ProtoMessage()    {}
func (*CombinedTestPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfe14786b7f13cd, []int{4}
}

func (m *CombinedTestPlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombinedTestPlan.Unmarshal(m, b)
}
func (m *CombinedTestPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombinedTestPlan.Marshal(b, m, deterministic)
}
func (m *CombinedTestPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombinedTestPlan.Merge(m, src)
}
func (m *CombinedTestPlan) XXX_Size() int {
	return xxx_messageInfo_CombinedTestPlan.Size(m)
}
func (m *CombinedTestPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_CombinedTestPlan.DiscardUnknown(m)
}

var xxx_messageInfo_CombinedTestPlan proto.InternalMessageInfo

func (m *CombinedTestPlan) GetTestPlan() []*TestPlan {
	if m != nil {
		return m.TestPlan
	}
	return nil
}

func init() {
	proto.RegisterType((*Image)(nil), "testplans.Image")
	proto.RegisterType((*BuildPayload)(nil), "testplans.BuildPayload")
	proto.RegisterType((*SchedulingRequirements)(nil), "testplans.SchedulingRequirements")
	proto.RegisterType((*TestPlan)(nil), "testplans.TestPlan")
	proto.RegisterType((*CombinedTestPlan)(nil), "testplans.CombinedTestPlan")
}

func init() { proto.RegisterFile("test_plan.proto", fileDescriptor_2dfe14786b7f13cd) }

var fileDescriptor_2dfe14786b7f13cd = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x5d, 0x8b, 0xd3, 0x4c,
	0x14, 0xc7, 0xb7, 0xed, 0xd3, 0x6d, 0x73, 0xd2, 0xd2, 0x32, 0x0f, 0x74, 0xc3, 0xa2, 0xb0, 0x46,
	0x58, 0x16, 0x84, 0x44, 0xd6, 0x1b, 0x41, 0xaf, 0xba, 0x2b, 0x56, 0x44, 0x2d, 0xb1, 0x78, 0xb1,
	0x37, 0x61, 0x92, 0x9c, 0x4c, 0x07, 0x92, 0x49, 0xcd, 0x4c, 0xbb, 0xf6, 0x7b, 0xfb, 0x01, 0x24,
	0x93, 0x34, 0x2f, 0xd0, 0xab, 0xe4, 0xbc, 0xfc, 0x7f, 0xf3, 0x72, 0xfe, 0x03, 0x33, 0x85, 0x52,
	0xf9, 0xbb, 0x84, 0x0a, 0x67, 0x97, 0x67, 0x2a, 0x23, 0x46, 0x91, 0x28, 0x62, 0x79, 0xfd, 0x23,
	0xd9, 0x87, 0x3c, 0x8c, 0x99, 0x8b, 0x7f, 0x14, 0xe6, 0x82, 0x26, 0x6e, 0x98, 0x67, 0xb2, 0xa8,
	0x73, 0xc1, 0x5c, 0xdd, 0xee, 0x86, 0x99, 0x88, 0x39, 0x73, 0x15, 0xcd, 0x19, 0x2a, 0x5f, 0xc3,
	0x72, 0xfc, 0xbd, 0xe7, 0x39, 0xa6, 0x28, 0x94, 0xf4, 0xcb, 0x7a, 0xc9, 0xb6, 0x6f, 0x61, 0xf8,
	0x25, 0xa5, 0x0c, 0xc9, 0x4b, 0x00, 0x5e, 0xfc, 0xf8, 0x82, 0xa6, 0x68, 0xf5, 0x6e, 0x7a, 0x77,
	0x86, 0x67, 0xe8, 0xcc, 0x77, 0x9a, 0xa2, 0xbd, 0x86, 0xc9, 0x72, 0xcf, 0x93, 0x68, 0x4d, 0x8f,
	0x49, 0x46, 0x23, 0x62, 0xc1, 0xe8, 0x80, 0xb9, 0xe4, 0x99, 0xa8, 0x7a, 0x4f, 0x21, 0xb9, 0x85,
	0xa1, 0x96, 0x59, 0xfd, 0x9b, 0xc1, 0x9d, 0x79, 0x3f, 0x77, 0xea, 0xdd, 0x3b, 0x7a, 0x25, 0xaf,
	0x2c, 0xdb, 0x47, 0x58, 0xfc, 0x0c, 0xb7, 0x18, 0xed, 0x13, 0x2e, 0x98, 0xd7, 0xda, 0x20, 0x79,
	0x03, 0xf3, 0x1c, 0x63, 0xcc, 0x51, 0x84, 0xe8, 0x47, 0x28, 0x39, 0xab, 0x16, 0x59, 0x5d, 0x78,
	0xb3, 0xba, 0xf2, 0xa8, 0x0b, 0xe4, 0x35, 0x4c, 0x82, 0x62, 0x63, 0x7e, 0x79, 0x5e, 0xab, 0x5f,
	0x35, 0x9a, 0x3a, 0xbb, 0xd1, 0xc9, 0xe5, 0x14, 0xcc, 0xd3, 0x75, 0x1c, 0x77, 0x68, 0xff, 0x1d,
	0xc0, 0x78, 0x83, 0x52, 0xad, 0x13, 0x2a, 0xc8, 0x07, 0x98, 0xb0, 0x10, 0xcb, 0x7b, 0x0a, 0x63,
	0xa6, 0x57, 0x32, 0xef, 0xaf, 0x9c, 0xd6, 0xc5, 0x3a, 0x9f, 0x43, 0x2c, 0xfa, 0x1f, 0x62, 0xb6,
	0xba, 0xf0, 0x80, 0xd5, 0x11, 0x79, 0x0f, 0xe6, 0xf6, 0xb9, 0xd1, 0xf6, 0xb5, 0x76, 0xd1, 0xd1,
	0xae, 0x9e, 0x1b, 0xa9, 0xb1, 0x3d, 0x05, 0xe4, 0x2b, 0x90, 0x34, 0x0b, 0x12, 0x1a, 0xf8, 0x87,
	0xb4, 0x01, 0x0c, 0x34, 0xe0, 0x45, 0x07, 0xf0, 0x4d, 0xb7, 0xfd, 0x4a, 0x1b, 0xcc, 0x2c, 0xed,
	0xa6, 0xc8, 0x27, 0x98, 0x2b, 0x2a, 0x55, 0x07, 0xf5, 0x9f, 0x46, 0x5d, 0x77, 0x50, 0x1b, 0x2a,
	0x55, 0x1b, 0x34, 0x55, 0xed, 0x44, 0x71, 0x9a, 0x36, 0x61, 0x78, 0xe6, 0x34, 0x6d, 0xb5, 0x71,
	0xa8, 0x95, 0x4f, 0x70, 0x25, 0xeb, 0x61, 0x76, 0xec, 0x66, 0x5d, 0x6a, 0xca, 0xab, 0x96, 0x0d,
	0xce, 0x8f, 0xdd, 0x5b, 0xc8, 0xf3, 0x76, 0xf8, 0x08, 0xd3, 0x72, 0xc2, 0xbb, 0xd2, 0x7b, 0xd6,
	0xa8, 0x9a, 0x50, 0x43, 0x6c, 0x5b, 0xd3, 0x2b, 0xfd, 0x50, 0x45, 0x4b, 0x03, 0x46, 0xd5, 0x26,
	0xed, 0x47, 0x98, 0x3f, 0x64, 0x69, 0xc0, 0x05, 0x46, 0xf5, 0xf4, 0xdf, 0x82, 0x51, 0x3f, 0x37,
	0xab, 0xa7, 0x1d, 0xfb, 0x7f, 0x0b, 0x7c, 0xea, 0xf3, 0xc6, 0xaa, 0xfa, 0x5b, 0x8e, 0x9f, 0x2e,
	0xf5, 0xd3, 0x91, 0x41, 0xf9, 0x7d, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x81, 0x34, 0xda, 0x55,
	0xb1, 0x03, 0x00, 0x00,
}
